name: Docker Image CI
on:
  push:
    branches:
    - aarch64
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: arm64
    steps:
    - uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push docker image
      with:
        image: github-actions-runner
        tags: aarch64
        registry: registry.nubificus.co.uk
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
