name: Docker Image CI
on:
  push:
    branches:
    - x86_64
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ludeeus/action-shellcheck@1.1.0
    #- uses: brpaz/hadolint-action@v1.4.0
    - run: |
        docker build . -t registry.nubificus.co.uk/github-actions-runner:x86_64
